[Hotfix] Fix ownership of the log file
rciam/check-in-validator-plugin pull request #3
Opened 2023-06-30 13:40 UTC by nikosev

# Summary

This PR introduces a fix the for ownership of the log file

2023-06-30 14:06 UTC, NicolasLiampotis requested changes
To avoid having to handle different user & group ownership depending on whether the plugin is used by HTCondor or ARC-CE sites I suggest that we change the log configuration to default to syslog only instead of syslog and file. If a site admin prefers syslog+file or just file they can modify `logger.ini` accordingly. So I'd propose the following changes:
1.  Change the default logger.ini installed by the RPM
2. Adjust the logging section of README to describe the new default behaviour (syslog only)
3. Remove the lines from the RPM that create the log file

2023-06-30 14:06 UTC, NicolasLiampotis commented on egi-check-in-validator.spec
> +%attr(0644,condor,condor) %{_localstatedir}/log/%{name}/egi-check-in-validator.log
We can remove the lines about creating the log files if the default is to use syslog

2023-06-30 15:35 UTC, nikosev commented
> 

I have made the required changes

2023-07-06 08:33 UTC, NicolasLiampotis approved these changes
LGTM

2023-07-06 08:34 UTC, merged